### ISSUE TITLE
I download it but I can't use it 

### ISSUE THREAD

**Issue by gokhangezgin** [asweigart/pyautogui#487] opened 2020-10-25 13:52 UTC
Hello I use cmd and pip. I download pyautogui but when I try to import in Pycharm it doesn't find anything. Can you help me

**Comment by jorg-j** [comment] 2020-10-25 20:49
Pycharm sets up a venv for each project. You need to install it within the venv.

**Comment by nimit2801** [comment] 2020-11-05 13:23
@gokhangezgin if the problem is solved please close the issue :) if you need any further assistance please the community will be more than happy to answer you. :)

**Closed** 2020-11-05 13:33 UTC
