### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by codewriter4** [asweigart/pyautogui#205] opened 2017-12-27 19:01 UTC
Any Python3 compatibility?

**Comment by linusg** [comment] 2017-12-27 20:57
Of course it runs under Python 3, why not? Have you even tried?

**Comment by Mardox91** [comment] 2018-01-04 19:11
I've been using it on python3 and it works.

**Comment by Blucknote** [comment] 2018-01-12 10:24
runing on python3 fine

**Comment by vikramdurai** [comment] 2018-02-25 06:13
@codewriter the general consensus seems to be that the issue is resolved, you should close the issue.

**Comment by afs2015** [comment] 2018-05-17 19:59
@asweigart: I believe this can be marked as closed. Should we add to the documentation that this project supports both Python 2 and Python 3?

**Comment by asweigart** [comment] 2018-05-17 20:06
Yes, we should note that in the documentation that PyAutoGUI is for both Pytho n2 and 3.

**Closed** 2018-05-17 20:06 UTC
