### ISSUE TITLE
[enhancement] Add Recording Feature

### ISSUE THREAD

**Issue by bntzio** [asweigart/pyautogui#191] opened 2017-10-17 22:15 UTC
Hey Al, amazing program and course! (Automate the Boring Stuff w/Python)

I was thinking, it'd be really cool a record feature in PyAutoGUI.

What I mean with a record feature is the ability to let's say, call a method (just like `displayMousePosition()`) add a delay of X seconds to start recording the movements of the cursor and then start recording those coordinates.

So that will allow users to record what they want to do in a more faster way, instead of checking the coordinates of various points they want to click/drag and then annotate them, they can record the actions they want to do in the program and replicate the behavior. In order to stop the recording, there should be kill-switch like a key combination on the keyboard, just like screen recorders do.

After the recording, PyAutoGUI can save the replicated movements/actions in a file specified by the user at the end of the recording, and use that program to replicate that behavior again.

What do you think? 🙂

**Comment by mirh** [comment] 2018-08-28 15:49
Duplicate of #127

**Comment by asweigart** [comment] 2020-01-14 09:30
Closing since this is a dupe of #127. But thanks for your interest in this feature. It's good to know what users want.

**Closed by asweigart** 2020-01-14 09:30 UTC
Labels: enhancement
