### ISSUE TITLE
Unable to run pyautogui scripts from remote headless server, I can run them fine from the linux machine

### ISSUE THREAD

**Issue by malak33** [asweigart/pyautogui#87] opened 2016-05-20 04:06 UTC
this is the output that I get when I try to run the script remotely:

qauser@sf-live-ep:~$ ./Automation2.sh
Traceback (most recent call last):
  File "./createMalwarePolicyFtpDown.py", line 9, in <module>
    import pyautogui
  File "/usr/local/lib/python3.4/dist-packages/pyautogui/**init**.py", line 81, in <module>
    import pyautogui._pyautogui_x11 as platformModule
  File "/usr/local/lib/python3.4/dist-packages/pyautogui/_pyautogui_x11.py", line 153, in <module>
    _display = Display(None) # TODO - Display() can have other values passed to it. Implement that later.
  File "/usr/local/lib/python3.4/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.4/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.**init**(_(self, ) + args, *_keys)
  File "/usr/local/lib/python3.4/dist-packages/Xlib/protocol/display.py", line 53, in **init**
    name, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python3.4/dist-packages/Xlib/support/connect.py", line 62, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python3.4/dist-packages/Xlib/support/unix_connect.py", line 47, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

**Comment by thaffenden** [comment] 2016-06-29 13:09
I've not tried it on Linux but from your description I think the route case of this would be the same ass issue #34 .
If you're running it headless, there is no display, so there is no GUI to interact with. 
As PyAutoGUI needs a GUI to run I don't think this is something that can be resolved.

**Comment by dragon788** [comment] 2017-01-24 03:56
@malak33 This may be a duplicate of #54, I'd suggest copying you comments over there and closing this one to increase the "weight" of that issue.

**Comment by asweigart** [comment] 2017-03-19 02:26
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.

**Closed by asweigart** 2017-03-19 02:26 UTC
