### ISSUE TITLE
Please remove the .pixel() and .pixelMatchesColor() 10,000 usage limit.

### ISSUE THREAD

**Issue by dantechguy** [asweigart/pyautogui#229] opened 2018-05-20 13:25 UTC
Took me a while to figure out what the problem was, but it came down to these two having a 10,000 usage limit. Please remove this, or let me know a way to circumvent the issue. Thank you!

**Comment by mogamepro** [comment] 2018-05-31 07:40
I'm guess that you're using Windows since it was breaking at approximately 10,000 uses for me as well. I don't know anything about this concerning the other OSes and the below probably doesn't apply to them.

There isn't a hardcoded limit. Pyautogui uses Pyscreeze for many of its functions such as the two you mentioned and the .pixelMatchesColor() function uses the .pixel function. In the pixel function it acquires a device context handler but never releases it. This causes it to fail after a number of uses.

I just spent the last few days troubleshooting the problem myself. It took me so long because it was the screenshot function that was failing. Giving me a PIL ImageGrab error. I added in a single line to release the device context handler in the pixel function and it stopped breaking, so I'm sure this was the issue I had.
asweigart/pyscreeze#33

After seeing [this SO answer (first comment on accepted answer)](https://stackoverflow.com/questions/3586046/fastest-way-to-take-a-screenshot-with-python-on-windows) I added in the fix in my copy of pyscreeze to verify and went to its repository to report the issue, only to see that there has been a fix just sitting there for the last half year...

Link to start of pyscreeze's pixel function:
https://github.com/asweigart/pyscreeze/blob/3da0575b746f38dcab0ff4d82d7aa280948aff58/pyscreeze/__init__.py#L423
MSDN docs on GetDC:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd144871(v=vs.85).aspx
and ReleaseDC:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd162920(v=vs.85).aspx

As for a workaround until when/if this gets fixed, maybe something like overriding the function similar to this SO question
https://stackoverflow.com/questions/10829200/override-module-method-where-from-import-is-used
Copy the function into your code and add the line `windll.user32.ReleaseDC(0, hdc)` before the return statement.

**Comment by ijknabla** [comment] 2019-03-07 04:24
I noticed this issue as my pull request was being referred to.
asweigart/pyscreeze#33

----

### environment
Windows 10 (64 bit) Python 3.6 pyautogui
### symptom
I created a color picker that acquires the color of the pixel indicated by the mouse cursor in real time (~ msec), the memory usage reached 100%, and Windows became unstable.

----

I had to respond to the same problem as this issue. As a result of checking with the Python debugger (pdb), I noticed that this problem is not in pyautogui itself, and there is a problem with the implementation of pyscreeze used by pyautogui.
As pointed out by @mogamepro, this problem is Windows specific. It is caused by pyscreeze.pixel() not releasing the device context handler.

Since the problem is in pyscreeze.pixel(), I think that if you modify pyscreeze.pixel () rather than pyautogui, you can fix bugs in packages using other pyscreeze as an better solution.

----
### to fix
pull asweigart/pyscreeze#33 and merge into newest master branch
and, running `setup.py install` as you like

**Comment by asweigart** [comment] 2019-05-17 17:16
Fixed with https://github.com/asweigart/pyscreeze/pull/33

**Closed by asweigart** 2019-05-17 17:16 UTC
