### ISSUE TITLE
the error " from PIL import Image ImportError: No module named 'PIL'"is displayed when install pyautogui, i using Mac.

### ISSUE THREAD

**Issue by sirodeng** [asweigart/pyautogui#119] opened 2017-01-10 02:00 UTC
System: Mac 10.12

goMac:~ Sapphire$ pip3 install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.33.zip
Collecting pymsgbox (from pyautogui)
  Using cached PyMsgBox-1.0.3.zip
Collecting PyTweening>=1.0.1 (from pyautogui)
  Using cached PyTweening-1.0.3.zip
Collecting Pillow (from pyautogui)
  Using cached Pillow-4.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyscreeze (from pyautogui)
  Using cached PyScreeze-0.1.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ll/r4qn51tn4_7bqbm82ldjyy7r0000gn/T/pip-build-mzsydqfb/pyscreeze/setup.py", line 6, in <module>
        version=__import__('pyscreeze').__version__,
      File "/private/var/folders/ll/r4qn51tn4_7bqbm82ldjyy7r0000gn/T/pip-build-mzsydqfb/pyscreeze/pyscreeze/__init__.py", line 21, in <module>
        from PIL import Image
    ImportError: No module named 'PIL'

**Comment by glitchassassin** [comment] 2017-01-10 14:03
Duplicate of #106, referencing a [known issue with pyscreeze](https://github.com/asweigart/pyscreeze/issues/20).

**Comment by glitchassassin** [comment] 2017-01-10 14:13
Try running `pip3 install pillow` first, and then `pip3 install pyautogui`.

**Comment by Constantor** [comment] 2017-01-16 11:13
Try `pip3 install image`, then `pip3 install pyautogui`.

**Comment by asweigart** [comment] 2017-03-18 23:25
Fixed in https://github.com/asweigart/pyscreeze/pull/17

**Closed by asweigart** 2017-03-18 23:25 UTC

**Comment by asweigart** [comment] 2017-03-19 02:16
Fixed in asweigart/pyscreeze#17

**Comment by atiartalukdar** [comment] 2017-11-24 04:54
use --user at last of your install command, so that the package will be installed only for the current user, not for all.

pip install xxxxxx --user
or
pip3 install xxxxxx --user
